# Generated by Django 5.2.8 on 2026-07-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='recurrence_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
