# Generated by Django 5.2.8 on 2026-07-13 21:08

import django.db.models.deletion
from django.db import migrations, models


def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('ALTER TABLE "household_shoppingprice" ENABLE ROW LEVEL SECURITY')
        cursor.execute('ALTER TABLE "household_shoppingprice" FORCE ROW LEVEL SECURITY')
        cursor.execute("CREATE POLICY household_isolation ON \"household_shoppingprice\" USING (household_id::text = current_setting('app.household_id', true)) WITH CHECK (household_id::text = current_setting('app.household_id', true))")


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('DROP POLICY IF EXISTS household_isolation ON "household_shoppingprice"')
        cursor.execute('ALTER TABLE "household_shoppingprice" DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0004_shoppingitem_recurrence_days'),
        ('households', '0003_householdinvite_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retailer', models.CharField(choices=[('ah', 'Albert Heijn'), ('jumbo', 'Jumbo'), ('lidl', 'Lidl'), ('kaufland', 'Kaufland')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_label', models.CharField(blank=True, max_length=60)),
                ('is_offer', models.BooleanField(default=False)),
                ('offer_label', models.CharField(blank=True, max_length=160)),
                ('product_url', models.URLField(blank=True)),
                ('observed_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='household.shoppingitem')),
            ],
            options={
                'ordering': ('price',),
                'constraints': [models.UniqueConstraint(fields=('item', 'retailer'), name='unique_price_per_item_retailer')],
            },
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
