# Generated by Django 5.2.8 on 2026-07-13 21:10

import django.db.models.deletion
import household.models
from django.db import migrations, models


def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('ALTER TABLE "household_receipt" ENABLE ROW LEVEL SECURITY')
        cursor.execute('ALTER TABLE "household_receipt" FORCE ROW LEVEL SECURITY')
        cursor.execute("CREATE POLICY household_isolation ON \"household_receipt\" USING (household_id::text = current_setting('app.household_id', true)) WITH CHECK (household_id::text = current_setting('app.household_id', true))")


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('DROP POLICY IF EXISTS household_isolation ON "household_receipt"')
        cursor.execute('ALTER TABLE "household_receipt" DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('household', '0005_shoppingprice'),
        ('households', '0003_householdinvite_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retailer', models.CharField(blank=True, max_length=120)),
                ('purchased_on', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.FileField(upload_to=household.models.receipt_upload_path)),
                ('ocr_text', models.TextField(blank=True)),
                ('ocr_status', models.CharField(choices=[('pending', 'Wacht op OCR'), ('complete', 'Herkenning klaar'), ('failed', 'Herkenning mislukt')], default='pending', max_length=20)),
                ('ocr_error', models.CharField(blank=True, max_length=300)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='finance.transaction')),
            ],
            options={
                'ordering': ('-purchased_on', '-created_at'),
            },
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
