# Generated by Django 5.2.8 on 2026-07-14 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0006_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='interval_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='routine',
            name='last_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='next_due_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
