# Generated by Django 5.2.8 on 2026-07-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0007_routine_interval_days_routine_last_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingprice',
            name='matched_product_name',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='shoppingprice',
            name='offer_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppingprice',
            name='regular_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='shoppingprice',
            name='source',
            field=models.CharField(choices=[('manual', 'Handmatig'), ('checkjebon', 'Checkjebon'), ('prijsprofeet', 'PrijsProfeet')], default='manual', max_length=20),
        ),
    ]
