# Generated by Django 5.2.8 on 2026-07-15 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0010_mealingredient'),
        ('households', '0003_householdinvite_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('unit', models.CharField(default='stuks', max_length=32)),
                ('minimum_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
            ],
            options={
                'ordering': ('category', 'name'),
                'constraints': [models.UniqueConstraint(fields=('household', 'name'), name='unique_household_pantry_item')],
            },
        ),
    ]
