# Generated by Django 5.2.8 on 2026-07-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0018_weather_rls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiptlineitem',
            options={},
        ),
    ]
