# Generated by Django 5.2.8 on 2026-07-16 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0019_receiptlineitem_meta_cleanup'),
        ('households', '0007_childprofile_rls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('position', 'created_at')},
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='task',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='household.tasklist'),
        ),
        migrations.AddConstraint(
            model_name='tasklist',
            constraint=models.UniqueConstraint(fields=('household', 'name'), name='unique_task_list_name'),
        ),
    ]
