# Generated by Django 5.2.8 on 2026-07-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0022_backfill_task_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by_agent',
            field=models.BooleanField(default=False),
        ),
    ]
