# Generated by Django 5.2.8 on 2026-07-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0023_task_completion_reason_task_created_by_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_label',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='task',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
