# Generated by Django 5.2.8 on 2026-07-19 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0024_task_source_label_task_source_url'),
        ('households', '0007_childprofile_rls'),
        ('integrations', '0025_remove_integrationconnection_unique_household_user_provider_connection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskListSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('outlook_todo', 'Microsoft To Do')], max_length=32)),
                ('external_list_id', models.CharField(max_length=240)),
                ('external_list_name', models.CharField(blank=True, max_length=160)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='external_id',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='task',
            name='external_provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='task',
            name='remote_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('household', 'external_provider', 'external_id'), name='unique_task_external_ref'),
        ),
        migrations.AddField(
            model_name='tasklistsync',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_list_syncs', to='integrations.integrationconnection'),
        ),
        migrations.AddField(
            model_name='tasklistsync',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AddField(
            model_name='tasklistsync',
            name='task_list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_link', to='household.tasklist'),
        ),
        migrations.AddConstraint(
            model_name='tasklistsync',
            constraint=models.UniqueConstraint(fields=('household', 'provider', 'external_list_id'), name='unique_task_list_sync_target'),
        ),
    ]
