# Generated by Django 5.2.8 on 2026-07-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_pushsubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='notificatio_user_id_f26de9_idx',
            old_name='notifications_user_id_created_at_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='delivered_to_openclaw_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
