# Generated by Django 5.2.8 on 2026-07-13 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('ALTER TABLE "integrations_integrationaudit" ENABLE ROW LEVEL SECURITY')
        cursor.execute('ALTER TABLE "integrations_integrationaudit" FORCE ROW LEVEL SECURITY')
        cursor.execute('DROP POLICY IF EXISTS household_isolation ON "integrations_integrationaudit"')
        cursor.execute("CREATE POLICY household_isolation ON \"integrations_integrationaudit\" USING (household_id::text = current_setting('app.household_id', true)) WITH CHECK (household_id::text = current_setting('app.household_id', true))")


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('DROP POLICY IF EXISTS household_isolation ON "integrations_integrationaudit"')
        cursor.execute('ALTER TABLE "integrations_integrationaudit" DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0003_householdinvite_label'),
        ('integrations', '0003_syncrun_household_and_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('action', models.CharField(choices=[('connected', 'Gekoppeld'), ('sync_succeeded', 'Synchronisatie geslaagd'), ('sync_failed', 'Synchronisatie mislukt'), ('disconnected', 'Ontkoppeld')], max_length=32)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='integrations.integrationconnection')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
