# Generated by Django 5.2.8 on 2026-07-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_integrationaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconnection',
            name='provider',
            field=models.CharField(choices=[('outlook', 'Outlook'), ('bunq', 'bunq'), ('hue', 'Philips Hue')], max_length=32),
        ),
    ]
