# Generated by Django 5.2.8 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("integrations", "0011_alter_integrationconnection_provider")]

    operations = [
        migrations.AlterField(
            model_name="integrationconnection",
            name="provider",
            field=models.CharField(choices=[("outlook", "Outlook"), ("bunq", "bunq"), ("hue", "Philips Hue"), ("sonos", "Sonos"), ("lg_thinq", "LG ThinQ"), ("google_home", "Google Home"), ("spotify", "Spotify"), ("smartcar", "Smartcar"), ("home_connect", "Home Connect")], max_length=32),
        ),
    ]
