# Generated by Django 5.2.8 on 2026-07-19 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0007_childprofile_rls'),
        ('integrations', '0012_alter_integrationconnection_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenClawToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='OpenClaw', max_length=120)),
                ('token_hash', models.CharField(max_length=255)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openclaw_tokens', to='households.household')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
