# Generated by Django 5.2.8 on 2026-07-19 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0007_childprofile_rls'),
        ('integrations', '0014_openclawtoken_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenClawActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='family-app', max_length=40)),
                ('action', models.CharField(max_length=40)),
                ('summary', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('success', 'Gelukt'), ('error', 'Mislukt')], default='success', max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openclaw_action_logs', to='households.household')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
