# Generated by Django 5.2.8 on 2026-07-19 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_openclawactionlog_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='openclawactionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openclaw_action_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openclawtoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openclaw_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
