# Generated by Django 5.2.8 on 2026-07-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_backfill_openclawtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='openclawtoken',
            name='scopes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
