# Generated by Django 5.2.8 on 2026-07-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0022_openclawnotificationpreference_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconnection',
            name='provider',
            field=models.CharField(choices=[('outlook', 'Outlook'), ('bunq', 'bunq'), ('hue', 'Philips Hue'), ('sonos', 'Sonos'), ('lg_thinq', 'LG ThinQ'), ('google_home', 'Google Home'), ('spotify', 'Spotify'), ('smartcar', 'Smartcar'), ('home_connect', 'Home Connect'), ('dropbox', 'Dropbox')], max_length=32),
        ),
    ]
