# Generated by Django 5.2.8 on 2026-07-19 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0007_childprofile_rls'),
        ('integrations', '0024_alter_integrationconnection_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='integrationconnection',
            name='unique_household_user_provider_connection',
        ),
        migrations.AddConstraint(
            model_name='integrationconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('provider', 'imap'), _negated=True), fields=('household', 'user', 'provider'), name='unique_household_user_provider_connection'),
        ),
        migrations.AddConstraint(
            model_name='integrationconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('provider', 'imap')), fields=('household', 'user', 'provider', 'external_account'), name='unique_household_user_imap_account'),
        ),
    ]
