# Generated by Django 5.2.8 on 2026-07-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_account_id', models.CharField(max_length=180)),
                ('name', models.CharField(max_length=160)),
                ('iban', models.CharField(blank=True, max_length=48)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('bunq', 'bunq'), ('abn_amro_manual', 'ABN AMRO import')], max_length=32)),
                ('display_name', models.CharField(max_length=160)),
                ('status', models.CharField(default='configured', max_length=24)),
                ('external_reference', models.CharField(blank=True, max_length=180)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecurringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.CharField(max_length=180)),
                ('merchant', models.CharField(max_length=240)),
                ('direction', models.CharField(choices=[('income', 'Inkomsten'), ('expense', 'Kosten')], max_length=12)),
                ('group', models.CharField(choices=[('fixed', 'Vaste lasten'), ('insurance', 'Verzekeringen'), ('credit', 'Leningen & credits'), ('subscription', 'Abonnementen'), ('tax', 'Belastingen'), ('other', 'Overig')], default='other', max_length=16)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cadence_days', models.PositiveIntegerField(default=30)),
                ('occurrence_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateField(blank=True, null=True)),
                ('user_confirmed', models.BooleanField(default=False)),
                ('is_excluded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_transaction_id', models.CharField(max_length=180)),
                ('booked_at', models.DateField()),
                ('description', models.TextField()),
                ('counterparty', models.CharField(blank=True, max_length=240)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('payment_type', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recurring_override', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-booked_at', '-id'),
            },
        ),
    ]
