# Generated by Django 5.2.8 on 2026-07-13 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance.bankconnection'),
        ),
        migrations.AddField(
            model_name='budget',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AddField(
            model_name='recurringrule',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AddConstraint(
            model_name='bankconnection',
            constraint=models.UniqueConstraint(fields=('household', 'provider', 'external_reference'), name='unique_household_finance_connection'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('connection', 'provider_account_id'), name='unique_provider_bank_account'),
        ),
        migrations.AddConstraint(
            model_name='recurringrule',
            constraint=models.UniqueConstraint(fields=('household', 'fingerprint'), name='unique_household_recurring_fingerprint'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['household', 'booked_at'], name='finance_tra_househo_4279ed_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['household', 'counterparty'], name='finance_tra_househo_2e18a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('account', 'provider_transaction_id'), name='unique_provider_transaction'),
        ),
    ]
