# Generated by Django 5.2.8 on 2026-07-13 21:00

import django.db.models.deletion
from django.db import migrations, models


HOME_TABLES = ("home_homeassistantconfig", "home_homeentity", "home_homeactionaudit")


def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in HOME_TABLES:
            cursor.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
            cursor.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
            cursor.execute(f'DROP POLICY IF EXISTS household_isolation ON "{table}"')
            cursor.execute(f"CREATE POLICY household_isolation ON \"{table}\" USING (household_id::text = current_setting('app.household_id', true)) WITH CHECK (household_id::text = current_setting('app.household_id', true))")


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in HOME_TABLES:
            cursor.execute(f'DROP POLICY IF EXISTS household_isolation ON "{table}"')
            cursor.execute(f'ALTER TABLE "{table}" DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0003_householdinvite_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAssistantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(max_length=500)),
                ('token_encrypted', models.TextField()),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_assistant', to='households.household')),
            ],
        ),
        migrations.CreateModel(
            name='HomeEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('is_available', models.BooleanField(default=True)),
                ('is_supported', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
            ],
            options={
                'ordering': ('domain', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HomeActionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('succeeded', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='home.homeentity')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='homeentity',
            constraint=models.UniqueConstraint(fields=('household', 'entity_id'), name='unique_home_entity_per_household'),
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
