# Generated by Django 5.2.8 on 2026-07-13 21:06

import django.db.models.deletion
import home.models
from django.conf import settings
from django.db import migrations, models


def enable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('ALTER TABLE "home_householddocument" ENABLE ROW LEVEL SECURITY')
        cursor.execute('ALTER TABLE "home_householddocument" FORCE ROW LEVEL SECURITY')
        cursor.execute('CREATE POLICY household_isolation ON "home_householddocument" USING (household_id::text = current_setting(\'app.household_id\', true)) WITH CHECK (household_id::text = current_setting(\'app.household_id\', true))')


def disable_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('DROP POLICY IF EXISTS household_isolation ON "home_householddocument"')
        cursor.execute('ALTER TABLE "home_householddocument" DISABLE ROW LEVEL SECURITY')


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_emergencycontact_maintenanceitem_room_furnishingitem_and_more'),
        ('households', '0003_householdinvite_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('file', models.FileField(upload_to=home.models.household_document_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RunPython(enable_rls, disable_rls),
    ]
