# Generated by Django 5.2.8 on 2026-07-14 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_householddocument'),
        ('integrations', '0005_alter_integrationconnection_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeentity',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_entities', to='integrations.integrationconnection'),
        ),
        migrations.AddField(
            model_name='homeentity',
            name='source',
            field=models.CharField(choices=[('home_assistant', 'Home Assistant'), ('hue', 'Philips Hue')], default='home_assistant', max_length=32),
        ),
    ]
