# Generated by Django 5.2.8 on 2026-07-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homeentity_connection_homeentity_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeentity',
            name='source',
            field=models.CharField(choices=[('home_assistant', 'Home Assistant'), ('hue', 'Philips Hue'), ('sonos', 'Sonos'), ('lg_thinq', 'LG ThinQ'), ('google_home', 'Google Home')], default='home_assistant', max_length=32),
        ),
    ]
