# Generated by Django 5.2.8 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_homeentity_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeentity",
            name="source",
            field=models.CharField(choices=[("home_assistant", "Home Assistant"), ("hue", "Philips Hue"), ("sonos", "Sonos"), ("nest_protect", "Nest Protect"), ("lg_thinq", "LG ThinQ"), ("google_home", "Google Home"), ("spotify", "Spotify"), ("smartcar", "Smartcar"), ("google_cast", "Google Cast"), ("philips_tv", "Philips TV")], default="home_assistant", max_length=32),
        ),
    ]
