# Generated by Django 5.2.8 on 2026-07-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdinvite',
            name='label',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
