from django.urls import path

from integrations import views

app_name = "integrations"
urlpatterns = [
    path("", views.index, name="index"),
    path("profiel/", views.save_profile, name="save_profile"),
    path("huishouden/", views.save_household, name="save_household"),
    path("gegevens/exporteren/", views.export_household_data, name="export_household_data"),
    path("lokale-probe/downloaden/", views.download_local_probe, name="download_local_probe"),
    path("lokale-probe/pairing/", views.create_local_probe_pairing, name="create_local_probe_pairing"),
    path("lokale-probe/<uuid:probe_id>/hue/<int:discovery_id>/koppelen/", views.link_local_hue_bridge, name="link_local_hue_bridge"),
    path("lokale-probe/<uuid:probe_id>/intrekken/", views.revoke_local_probe, name="revoke_local_probe"),
    path("api/lokale-probe/pair/", views.local_probe_pair, name="local_probe_pair"),
    path("outlook/configuratie/", views.save_outlook_config, name="save_outlook_config"),
    path("outlook/start/", views.start_outlook, name="start_outlook"),
    path("outlook/callback/", views.outlook_callback, name="outlook_callback"),
    path("bunq/configuratie/", views.save_bunq_config, name="save_bunq_config"),
    path("bunq/start/", views.start_bunq, name="start_bunq"),
    path("bunq/callback/", views.bunq_callback, name="bunq_callback"),
    path("hue/configuratie/", views.save_hue_config, name="save_hue_config"),
    path("hue/start/", views.start_hue, name="start_hue"),
    path("hue/callback/", views.hue_callback, name="hue_callback"),
    path("sonos/configuratie/", views.save_sonos_config, name="save_sonos_config"),
    path("sonos/start/", views.start_sonos, name="start_sonos"),
    path("sonos/callback/", views.sonos_callback, name="sonos_callback"),
    path("sonos/events/<int:household_id>/<str:callback_token>/", views.sonos_event_callback, name="sonos_event_callback"),
    path("sonos/events/<int:household_id>/<str:callback_token>/<path:event_path>", views.sonos_event_callback, name="sonos_event_callback_path"),
    path("spotify/configuratie/", views.save_spotify_config, name="save_spotify_config"),
    path("spotify/start/", views.start_spotify, name="start_spotify"),
    path("spotify/callback/", views.spotify_callback, name="spotify_callback"),
    path("home-connect/configuratie/", views.save_home_connect_config, name="save_home_connect_config"),
    path("home-connect/start/", views.start_home_connect, name="start_home_connect"),
    path("home-connect/callback/", views.home_connect_callback, name="home_connect_callback"),
    path("smartcar/configuratie/", views.save_smartcar_config, name="save_smartcar_config"),
    path("smartcar/start/", views.start_smartcar, name="start_smartcar"),
    path("smartcar/callback/", views.smartcar_callback, name="smartcar_callback"),
    path("google-home/configuratie/", views.save_google_home_config, name="save_google_home_config"),
    path("google-home/start/", views.start_google_home, name="start_google_home"),
    path("google-home/callback/", views.google_home_callback, name="google_home_callback"),
    path("lg-thinq/configuratie/", views.save_lg_thinq_config, name="save_lg_thinq_config"),
    path("lg-thinq/start/", views.start_lg_thinq, name="start_lg_thinq"),
    path("lg-thinq/callback/", views.lg_thinq_callback, name="lg_thinq_callback"),
    path("hue/<int:connection_id>/bridge/start/", views.arm_hue_bridge, name="arm_hue_bridge"),
    path("hue/<int:connection_id>/bridge/voltooien/", views.finish_hue_bridge, name="finish_hue_bridge"),
    path("<int:connection_id>/synchroniseren/", views.sync_connection, name="sync_connection"),
    path("<int:connection_id>/ontkoppelen/", views.disconnect_connection, name="disconnect_connection"),
]
