# Generated by Django 5.2.8 on 2026-07-13 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulletinpost',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AddField(
            model_name='contact',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='family.contact'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AddField(
            model_name='wishitem',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wishitem',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='family.wishlist'),
        ),
    ]
