# Generated by Django 5.2.8 on 2026-07-13 19:44

import django.db.models.deletion
from django.db import migrations, models


def clear_empty_share_tokens(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('ALTER TABLE "family_wishlist" NO FORCE ROW LEVEL SECURITY')
            try:
                cursor.execute("UPDATE family_wishlist SET share_token = NULL WHERE share_token = ''")
            finally:
                cursor.execute('ALTER TABLE "family_wishlist" FORCE ROW LEVEL SECURITY')
        return
    WishList = apps.get_model("family", "WishList")
    WishList.objects.filter(share_token="").update(share_token=None)


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='share_token',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.RunPython(clear_empty_share_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='wishlist',
            name='share_token',
            field=models.CharField(blank=True, max_length=48, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='WishReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='family.wishitem')),
            ],
        ),
    ]
