# Generated by Django 5.2.8 on 2026-07-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_limit_public_wishlist_writes'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishitem',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
