# Generated by Django 5.2.8 on 2026-07-25 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0007_reapply_public_wishlist_policy'),
        ('households', '0007_childprofile_rls'),
        ('planning', '0007_outlook_sources_write_back_ready'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('question__sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EventGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('rsvp', models.CharField(choices=[('yes', 'Komt'), ('no', 'Komt niet'), ('maybe', 'Misschien')], default='yes', max_length=8)),
                ('party_size', models.PositiveSmallIntegerField(default=1)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EventInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=48, null=True, unique=True)),
                ('intro', models.TextField(blank=True)),
                ('rsvp_deadline', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.CharField(blank=True, max_length=40)),
                ('description', models.CharField(max_length=240)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EventQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('text', 'Tekst'), ('yesno', 'Ja of nee'), ('number', 'Aantal')], default='text', max_length=16)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='EventVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('postal_code', models.CharField(blank=True, max_length=24)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='eventanswer',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AddField(
            model_name='eventguest',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AddField(
            model_name='eventanswer',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='planning.eventguest'),
        ),
        migrations.AddField(
            model_name='eventinvite',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='planning.calendarevent'),
        ),
        migrations.AddField(
            model_name='eventinvite',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AddField(
            model_name='eventinvite',
            name='wishlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_invites', to='family.wishlist'),
        ),
        migrations.AddField(
            model_name='eventguest',
            name='invite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='planning.eventinvite'),
        ),
        migrations.AddField(
            model_name='eventprogramitem',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AddField(
            model_name='eventprogramitem',
            name='invite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='planning.eventinvite'),
        ),
        migrations.AddField(
            model_name='eventquestion',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AddField(
            model_name='eventquestion',
            name='invite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='planning.eventinvite'),
        ),
        migrations.AddField(
            model_name='eventanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='planning.eventquestion'),
        ),
        migrations.AddField(
            model_name='eventvenue',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='households.household'),
        ),
        migrations.AddField(
            model_name='eventinvite',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='planning.eventvenue'),
        ),
        migrations.AddConstraint(
            model_name='eventvenue',
            constraint=models.UniqueConstraint(fields=('household', 'name'), name='unique_event_venue_name_per_household'),
        ),
    ]
