import type { AppData } from "@/lib/types";

export const demoData: AppData = {
  household: {
    id: "demo-household",
    name: "Ons gezin",
    owner_id: "demo-user-1",
  },
  householdPreferences: {
    household_id: "demo-household",
    week_starts_on: "monday",
    default_dashboard: "vandaag",
    default_shopping_store: "Albert Heijn",
    quiet_hours_start: "22:00",
    quiet_hours_end: "07:00",
  },
  members: [
    {
      household_id: "demo-household",
      user_id: "demo-user-1",
      role: "owner",
      profile: { id: "demo-user-1", full_name: "Fatih", email: "fatih@example.com" },
    },
    {
      household_id: "demo-household",
      user_id: "demo-user-2",
      role: "member",
      profile: { id: "demo-user-2", full_name: "Gezinslid", email: "gezin@example.com" },
    },
  ],
  householdContacts: [
    {
      id: "contact-1",
      household_id: "demo-household",
      name: "Huisarts",
      relationship: "Zorg",
      phone: "020 123 4567",
      email: null,
      address: "Dorpsstraat 12",
      notes: "Spoed via praktijknummer buiten kantooruren.",
      priority: "belangrijk",
    },
    {
      id: "contact-2",
      household_id: "demo-household",
      name: "Buren",
      relationship: "Sleuteladres",
      phone: "06 12345678",
      email: null,
      address: null,
      notes: "Reserve sleutel ligt daar.",
      priority: "normaal",
    },
  ],
  householdInfoItems: [
    {
      id: "info-1",
      household_id: "demo-household",
      title: "Meterkast",
      category: "Huis",
      value: "Hal beneden",
      notes: "Hoofdschakelaar linksboven.",
      is_sensitive: false,
    },
    {
      id: "info-2",
      household_id: "demo-household",
      title: "Wifi gastnetwerk",
      category: "Techniek",
      value: "Gezinsgast",
      notes: "Wachtwoord alleen delen met bezoek.",
      is_sensitive: true,
    },
  ],
  maintenanceItems: [
    {
      id: "maintenance-1",
      household_id: "demo-household",
      title: "Rookmelders testen",
      area: "Veiligheid",
      provider: null,
      due_date: "2026-07-15",
      frequency: "monthly",
      status: "open",
      notes: "Testknop indrukken en batterijen controleren.",
      completed_at: null,
    },
    {
      id: "maintenance-2",
      household_id: "demo-household",
      title: "CV-ketel onderhoud",
      area: "Techniek",
      provider: "Installateur",
      due_date: "2026-09-01",
      frequency: "yearly",
      status: "open",
      notes: "Onderhoudscontract controleren.",
      completed_at: null,
    },
  ],
  householdNotes: [
    {
      id: "note-1",
      household_id: "demo-household",
      title: "Vrijdag afval aan de straat",
      body: "Groene bak en papier staan deze week op de planning.",
      category: "Huis",
      pinned: true,
      expires_at: "2026-07-12",
      created_by: "demo-user-1",
      created_at: "2026-07-10T08:00:00.000Z",
    },
    {
      id: "note-2",
      household_id: "demo-household",
      title: "Sporttas klaarzetten",
      body: "Zaterdag ochtend vroeg weg, schoenen en bidon vanavond klaarzetten.",
      category: "Kinderen",
      pinned: false,
      expires_at: null,
      created_by: "demo-user-2",
      created_at: "2026-07-09T18:30:00.000Z",
    },
  ],
  householdDocuments: [
    {
      id: "document-1",
      household_id: "demo-household",
      title: "Reisdocument Fatih",
      category: "Identiteit",
      owner_name: "Fatih",
      location: "Kluis map documenten",
      reference: "Paspoort",
      expires_at: "2027-05-10",
      notes: "Op tijd verlengen voor zomervakantie.",
      is_sensitive: true,
      created_at: "2026-07-10T10:00:00.000Z",
    },
    {
      id: "document-2",
      household_id: "demo-household",
      title: "Garantie wasmachine",
      category: "Garantie",
      owner_name: null,
      location: "Mail en map Huis",
      reference: "Factuur Coolblue",
      expires_at: "2028-02-01",
      notes: "Serienummer op achterkant apparaat.",
      is_sensitive: false,
      created_at: "2026-07-09T11:00:00.000Z",
    },
  ],
  taskIntegrations: [
    {
      id: "task-integration-1",
      household_id: "demo-household",
      provider: "microsoft_todo",
      status: "needs_auth",
      sync_direction: "two_way",
      display_name: "Microsoft To Do",
      last_sync_at: null,
    },
    {
      id: "task-integration-2",
      household_id: "demo-household",
      provider: "apple_reminders",
      status: "planned",
      sync_direction: "import_only",
      display_name: "Apple Herinneringen",
      last_sync_at: null,
    },
  ],
  tasks: [
    {
      id: "task-1",
      household_id: "demo-household",
      title: "Container aan de straat zetten",
      description: null,
      assignee_id: "demo-user-1",
      status: "open",
      priority: "normaal",
      due_date: new Date().toISOString().slice(0, 10),
    },
    {
      id: "task-2",
      household_id: "demo-household",
      title: "Verzekeringen controleren",
      description: null,
      assignee_id: null,
      status: "open",
      priority: "hoog",
      due_date: null,
    },
    {
      id: "task-3",
      household_id: "demo-household",
      title: "Schooltas klaarzetten",
      description: null,
      assignee_id: "demo-user-2",
      status: "done",
      priority: "laag",
      due_date: new Date().toISOString().slice(0, 10),
    },
  ],
  shoppingList: {
    id: "shopping-list-1",
    household_id: "demo-household",
    name: "Boodschappen",
  },
  shoppingItems: [
    {
      id: "shop-1",
      list_id: "shopping-list-1",
      household_id: "demo-household",
      product_id: "product-1",
      name: "Havermelk",
      category: "Zuivel",
      quantity: "2 pakken",
      checked: false,
    },
    {
      id: "shop-2",
      list_id: "shopping-list-1",
      household_id: "demo-household",
      product_id: "product-2",
      name: "Tomaten",
      category: "Groente",
      quantity: "500 gram",
      checked: false,
    },
    {
      id: "shop-3",
      list_id: "shopping-list-1",
      household_id: "demo-household",
      product_id: "product-3",
      name: "Vaatwastabletten",
      category: "Drogist",
      quantity: null,
      checked: true,
    },
  ],
  shoppingProducts: [
    {
      id: "product-1",
      household_id: "demo-household",
      name: "Havermelk",
      category: "Zuivel",
      default_quantity: "2 pakken",
      recurrence: "weekly",
      purchase_count: 8,
      last_purchased_at: "2026-07-08T09:20:00.000Z",
    },
    {
      id: "product-2",
      household_id: "demo-household",
      name: "Tomaten",
      category: "Groente",
      default_quantity: "500 gram",
      recurrence: "weekly",
      purchase_count: 6,
      last_purchased_at: "2026-07-08T09:20:00.000Z",
    },
    {
      id: "product-3",
      household_id: "demo-household",
      name: "Vaatwastabletten",
      category: "Drogist",
      default_quantity: null,
      recurrence: "monthly",
      purchase_count: 3,
      last_purchased_at: "2026-07-01T10:00:00.000Z",
    },
  ],
  mealPlans: [
    {
      id: "meal-1",
      household_id: "demo-household",
      planned_date: "2026-07-10",
      meal_type: "avondeten",
      title: "Pasta pesto",
      notes: "Snel klaar na werk.",
      ingredients: "Pasta\nPesto\nTomaten\nParmezaan",
    },
    {
      id: "meal-2",
      household_id: "demo-household",
      planned_date: "2026-07-11",
      meal_type: "lunch",
      title: "Broodjes gezond",
      notes: null,
      ingredients: "Broodjes\nKaas\nKomkommer\nEieren",
    },
  ],
  priceObservations: [
    {
      id: "price-1",
      household_id: "demo-household",
      product_id: "product-1",
      product_name: "Havermelk",
      store: "Albert Heijn",
      observed_at: "2026-07-08T09:20:00.000Z",
      unit_price_cents: 189,
      total_price_cents: 378,
      quantity: "2 pakken",
      source: "ocr",
    },
    {
      id: "price-2",
      household_id: "demo-household",
      product_id: "product-1",
      product_name: "Havermelk",
      store: "Albert Heijn",
      observed_at: "2026-06-24T09:20:00.000Z",
      unit_price_cents: 179,
      total_price_cents: 358,
      quantity: "2 pakken",
      source: "ocr",
    },
    {
      id: "price-3",
      household_id: "demo-household",
      product_id: "product-2",
      product_name: "Tomaten",
      store: "Albert Heijn",
      observed_at: "2026-07-08T09:20:00.000Z",
      unit_price_cents: 249,
      total_price_cents: 249,
      quantity: "500 gram",
      source: "ocr",
    },
  ],
  shoppingScans: [
    {
      id: "scan-1",
      household_id: "demo-household",
      status: "processed",
      source_filename: "bon-albert-heijn.jpg",
      extracted_text: "HAVERMELK 2 x 1.89\nTOMATEN 2.49\nTOTAAL 6.27",
      created_at: "2026-07-08T09:22:00.000Z",
    },
  ],
  financeItems: [
    {
      id: "finance-1",
      household_id: "demo-household",
      title: "Hypotheek",
      category: "Wonen",
      amount_cents: 145000,
      frequency: "maandelijks",
      due_date: "2026-07-28",
      status: "actief",
    },
    {
      id: "finance-2",
      household_id: "demo-household",
      title: "Energie",
      category: "Vaste lasten",
      amount_cents: 21800,
      frequency: "maandelijks",
      due_date: "2026-07-20",
      status: "actief",
    },
    {
      id: "finance-3",
      household_id: "demo-household",
      title: "Streaming",
      category: "Abonnementen",
      amount_cents: 1799,
      frequency: "maandelijks",
      due_date: "2026-07-15",
      status: "actief",
    },
  ],
  financeBudgets: [
    {
      id: "budget-1",
      household_id: "demo-household",
      category: "Wonen",
      monthly_limit_cents: 160000,
      alert_threshold: 0.85,
    },
    {
      id: "budget-2",
      household_id: "demo-household",
      category: "Vaste lasten",
      monthly_limit_cents: 35000,
      alert_threshold: 0.8,
    },
    {
      id: "budget-3",
      household_id: "demo-household",
      category: "Abonnementen",
      monthly_limit_cents: 6000,
      alert_threshold: 0.75,
    },
  ],
  bankConnections: [
    {
      id: "bank-connection-1",
      household_id: "demo-household",
      provider: "bunq",
      environment: "sandbox",
      status: "configured",
      last_sync_at: "2026-07-08T18:30:00.000Z",
    },
  ],
  bankAccounts: [
    {
      id: "bank-account-1",
      household_id: "demo-household",
      connection_id: "bank-connection-1",
      provider_account_id: "bunq-demo-main",
      name: "bunq Main",
      iban: "NL00BUNQ0123456789",
      currency: "EUR",
      balance_cents: 284250,
    },
    {
      id: "bank-account-2",
      household_id: "demo-household",
      connection_id: "bank-connection-1",
      provider_account_id: "bunq-demo-savings",
      name: "Buffer",
      iban: "NL00BUNQ9876543210",
      currency: "EUR",
      balance_cents: 1250000,
    },
  ],
  bankTransactions: [
    {
      id: "bank-transaction-1",
      household_id: "demo-household",
      connection_id: "bank-connection-1",
      account_id: "bank-account-1",
      provider_transaction_id: "payment-1",
      booked_at: "2026-07-08T09:20:00.000Z",
      description: "Albert Heijn",
      counterparty: "Albert Heijn",
      amount_cents: -4287,
      currency: "EUR",
      category: "Boodschappen",
    },
    {
      id: "bank-transaction-2",
      household_id: "demo-household",
      connection_id: "bank-connection-1",
      account_id: "bank-account-1",
      provider_transaction_id: "payment-2",
      booked_at: "2026-07-07T14:10:00.000Z",
      description: "Salaris",
      counterparty: "Werkgever",
      amount_cents: 385000,
      currency: "EUR",
      category: "Inkomen",
    },
    {
      id: "bank-transaction-3",
      household_id: "demo-household",
      connection_id: "bank-connection-1",
      account_id: "bank-account-1",
      provider_transaction_id: "payment-3",
      booked_at: "2026-07-06T18:45:00.000Z",
      description: "Netflix",
      counterparty: "Netflix",
      amount_cents: -1799,
      currency: "EUR",
      category: "Abonnementen",
    },
  ],
  recurringTransactionRules: [],
  calendarEvents: [
    {
      id: "event-1",
      household_id: "demo-household",
      integration_id: "calendar-integration-1",
      external_event_id: "outlook-event-1",
      external_calendar_id: "primary",
      external_calendar_name: "Prive",
      source_provider: "outlook",
      title: "Tandarts",
      starts_at: "2026-07-10T08:30:00.000Z",
      ends_at: null,
      location: "Centrum",
      participant_ids: ["demo-user-2"],
      is_all_day: false,
      organizer_name: "Fatih",
      web_link: null,
    },
    {
      id: "event-2",
      household_id: "demo-household",
      title: "Weekboodschappen",
      starts_at: "2026-07-11T09:00:00.000Z",
      ends_at: null,
      location: "Supermarkt",
      participant_ids: ["demo-user-1"],
      is_all_day: false,
      organizer_name: null,
      web_link: null,
    },
  ],
  calendarIntegrations: [
    {
      id: "calendar-integration-1",
      household_id: "demo-household",
      user_id: "demo-user-1",
      provider: "outlook",
      status: "configured",
      display_name: "Outlook prive agenda",
      account_email: "fatih@example.com",
      tenant_id: "consumers",
      last_sync_at: "2026-07-10T08:00:00.000Z",
    },
  ],
  hasHomeAssistantConfig: false,
  hasHueConfig: false,
  smartHomeIntegrations: [
    {
      id: "smart-home-google-1",
      household_id: "demo-household",
      provider: "google_home",
      mode: "nest_sdm",
      status: "needs_auth",
      display_name: "Google Nest SDM",
      project_id: null,
      last_sync_at: null,
    },
  ],
  smartHomeDevices: [],
  wishlistShares: [
    {
      id: "wishlist-share-1",
      household_id: "demo-household",
      title: "Verlanglijst Ons gezin",
      public_token: "demo-wishlist",
      enabled: true,
      created_at: "2026-07-10T09:00:00.000Z",
      updated_at: "2026-07-10T09:00:00.000Z",
    },
  ],
  wishlistItems: [
    {
      id: "wishlist-1",
      household_id: "demo-household",
      title: "LEGO set",
      description: "Voor verjaardag, voorkeur voor city of space.",
      url: "https://example.com/lego",
      image_url: null,
      desired_by: "Gezinslid",
      category: "Verjaardag",
      price_cents: 3499,
      priority: "hoog",
      status: "open",
      purchase_mode: "single",
      purchase_count: 0,
      is_public: true,
      reserved_by_name: null,
      reserved_at: null,
      purchased_at: null,
      last_purchased_at: null,
      created_at: "2026-07-10T09:10:00.000Z",
    },
    {
      id: "wishlist-2",
      household_id: "demo-household",
      title: "Noise cancelling koptelefoon",
      description: "Mag ook tweedehands als hij netjes is.",
      url: null,
      image_url: null,
      desired_by: "Fatih",
      category: "Tech",
      price_cents: 12000,
      priority: "normaal",
      status: "reserved",
      purchase_mode: "repeatable",
      purchase_count: 1,
      is_public: true,
      reserved_by_name: "Opa",
      reserved_at: "2026-07-11T12:00:00.000Z",
      purchased_at: null,
      last_purchased_at: "2026-07-11T12:00:00.000Z",
      created_at: "2026-07-09T18:00:00.000Z",
    },
  ],
};
